### ISSUE TITLE
Cleaned Up Filtered Data still looks suspect

### ISSUE THREAD

**Issue by mjunkmyjunk** [alan-couzens/python_for_coaches#1]
Edit: When I was writing this, I haven't yet finished reading Marco's Colab (https://colab.research.google.com/drive/1GUZVjZGhc2_JqV-J5m1mgbvbiTBV9WzZ?usp=sharing#scrollTo=wle7dowBJO61) so, I most likely missed a few things.  

Thanks v much for the write up. 
I was playing around with it and found that the 25% didn't quite work for my case.

I found that the 25% only removes 1 of the offending artifact and not the successive ones. Hence the artifact still survives through the filter.

eg: 
with this dummy dataset, the 5,5,5,5 only gets removed once.
`RRs = [0.476,0.476,5,5,5,5,5,5,5.418,0.285,2.281,0.285,0.285]`

<img width="1965" alt="Screenshot 2021-02-28 at 5 20 29 PM" src="https://user-images.githubusercontent.com/56195569/109413611-50827580-79e9-11eb-9ef4-f5a09b0382e9.png">

So what I did was to tweak this to become this.
```
for i in range(len(RRs)):
  if len(filtered_RRs) > 0:
    yy = (RRs[i] - filtered_RRs[len(filtered_RRs)-1])/filtered_RRs[len(filtered_RRs)-1]

  else:
    yy = 0.0

  if  abs(yy) < 0.25:
    filtered_RRs.append(RRs[i])
```

which results in this output which only adds to the filtered array if it's within 25% of the previous data(which was already appended in the filtered array). 

I'm not sure what to make of the data (yet) as I'm still going through your example and Marco Altini's colab.

But thanks very much for the tutorial. I also learned (bit of) python. 
<img width="2009" alt="Screenshot 2021-02-28 at 5 20 35 PM" src="https://user-images.githubusercontent.com/56195569/109413716-c25abf00-79e9-11eb-8745-af2895581626.png">

**Comment by alan-couzens** [comment]
Thanks @mjunkmyjunk , it looks like your dataset came from a training session rather than a resting HRV test. This is going to be more susceptible to artifacts. Your approach is correct though. It is easy to see the artifacts from your graph when compared to the regular data & it is important to remove them before calculating any HRV exercise metrics e.g. DFA alpha 1. Thanks for your comment!

**Comment by davidzof** [comment]
I agree @mjunkmyjunk including previously filtered values in your comparison doesn't work. I would also prefilter all values below your minHR (-10) say) in the first loop, say

            if RR_interval is not None and RR_interval < 1.5:
